#include <sstream>
#include <vector>

#include "cata_catch.h"
#include "character.h"
#include "json_loader.h"
#include "map_helpers.h"
#include "vehicle.h"
#include "veh_type.h"

static const vproto_id vehicle_prototype_veh_export_test( "veh_export_test" );
static const vproto_id vehicle_prototype_none( "none" );
static const itype_id itype_welder( "welder" );
static const vpart_id vpart_frame( "frame" );
static const vpart_id vpart_jumper_cable( "jumper_cable" );
static const vpart_id vpart_tools_fabrication( "veh_tools_fabrication" );

TEST_CASE( "export_vehicle_as_prototype" )
{
    clear_map();
    vehicle *veh_ptr = get_map().add_vehicle( vehicle_prototype_veh_export_test, tripoint_zero,
                       0_degrees, -1, 0 );
    REQUIRE( veh_ptr != nullptr );

    veh_ptr->set_owner( get_player_character() );
    veh_ptr->place_zones( get_map() );
    veh_ptr->refresh();
    veh_ptr->refresh_zones();

    std::ostringstream output;
    JsonOut json( output );
    vehicle_prototype::save_vehicle_as_prototype( *veh_ptr, json );
    const std::string expected =
        R"({"//1":"Although this vehicle can be readily spawned in game without further tweaking,","//2":"this is auto-generated by program, so please check against it before proceeding.","//3":"Only simple top-level items can be exported by this function.  Do not rely on this for exporting comestibles, containers, etc.","id":"/TO_BE_REPLACED/","type":"vehicle","name":"/TO_BE_REPLACED/","blueprint":["tH"],"parts":[{"x":0,"y":0,"parts":["frame",{"part":"tank_medium","fuel":"diesel"},"diesel_engine_v6","alternator_car","turret_mount",{"part":"turret_m240","ammo":100,"ammo_types":"762_51","ammo_qty":[500,500]},"seat"]},{"x":0,"y":1,"parts":["frame","trunk"]}],"items":[{"x":0,"y":1,"chance":100,"items":["saw"]}],"zones":[{"x":0,"y":1,"type":"LOOT_GUNS"}]})";
    CHECK( output.str() == expected );

    JsonValue exported_json = json_loader::from_string( output.str() );
    JsonObject exported_object = exported_json.get_object();
    CHECK( exported_object.get_string( "type" ) == "vehicle" );
    CHECK( exported_object.get_string( "id" ) == "/TO_BE_REPLACED/" );
}

TEST_CASE( "vehicle_prototype_export_fails_before_writing_invalid_json" )
{
    clear_map();
    vehicle *veh_ptr = get_map().add_vehicle( vehicle_prototype_veh_export_test, tripoint_zero,
                       0_degrees, -1, 0 );
    REQUIRE( veh_ptr != nullptr );

    // Attached cables are valid runtime parts, but NOINSTALL prevents them from being represented
    // by a loadable vehicle prototype.
    REQUIRE( veh_ptr->install_part( point_zero, vpart_jumper_cable, "", true ) >= 0 );

    std::ostringstream output;
    JsonOut json( output );
    CHECK_THROWS( vehicle_prototype::save_vehicle_as_prototype( *veh_ptr, json ) );
    CHECK( output.str().empty() );
}

TEST_CASE( "vehicle_prototype_export_preserves_attached_tool_state",
           "[vehicle][tools][prototype][export]" )
{
    clear_map();
    vehicle *veh = get_map().add_vehicle( vehicle_prototype_none, tripoint_zero, 0_degrees );
    REQUIRE( veh != nullptr );
    REQUIRE( veh->install_part( point_zero, vpart_frame, "", true ) >= 0 );
    const int station = veh->install_part( point_zero, vpart_tools_fabrication, "", true );
    REQUIRE( station >= 0 );
    item attached_welder( itype_welder, calendar::turn_zero );
    attached_welder.invlet = 'w';
    attached_welder.set_damage( 1000 );
    attached_welder.set_var( "prototype_test", "kept" );
    veh->get_tools( veh->part( station ) ).emplace_back( attached_welder );

    std::ostringstream output;
    JsonOut json( output );
    vehicle_prototype::save_vehicle_as_prototype( *veh, json );

    JsonValue exported_json = json_loader::from_string( output.str() );
    JsonArray part_groups = exported_json.get_object().get_array( "parts" );
    REQUIRE( part_groups.size() == 1 );
    JsonArray parts = part_groups.get_object( 0 ).get_array( "parts" );
    REQUIRE( parts.size() == 2 );
    JsonArray tools = parts.get_object( 1 ).get_array( "tools" );
    REQUIRE( tools.size() == 1 );

    item restored;
    restored.deserialize( tools.get_object( 0 ) );
    CHECK( restored.typeId() == itype_welder );
    CHECK( restored.invlet == 'w' );
    CHECK( restored.damage() == attached_welder.damage() );
    CHECK( restored.get_var( "prototype_test" ) == "kept" );
}
